#!/usr/local/bin/konoha

OUT << "Content-Type: text/plain" << EOL << EOL;

//Bytes b = new byte[$env.CONTENT_LENGTH];
//IN.read(b, 0, |b|);
//print b.decode();

//----- Register User Account -----
/*
1.script by using konoha.sql
2.make the user's repo on git by git cmd
*/

//----- Login User -----
/*
script by using konoha.sql
*/

//----- Find Friends -----
/*
script by using konoha.sql
*/

//----- Add Friends -----
/*
script by using konoha.sql
*/

